/// List of major banks in the Philippines
class PhilippineBanks {
  static const List<String> banks = [
    'BDO Unibank',
    'BPI (Bank of the Philippine Islands)',
    'Metrobank',
    'LandBank of the Philippines',
    'PNB (Philippine National Bank)',
    'Security Bank',
    'UnionBank',
    'RCBC (Rizal Commercial Banking Corporation)',
    'Chinabank',
    'EastWest Bank',
    'UCPB (United Coconut Planters Bank)',
    'Maybank Philippines',
    'HSBC Philippines',
    'Citibank Philippines',
    'CTBC Bank Philippines',
    'PBCom (Philippine Bank of Communications)',
    'Asia United Bank',
    'Robinsons Bank',
    'Sterling Bank of Asia',
    'Philippine Veterans Bank',
  ];
}

/// List of major cities in the Philippines
class PhilippineCities {
  static const List<String> cities = [
    'Manila',
    'Quezon City',
    'Caloocan',
    'Davao City',
    'Cebu City',
    'Zamboanga City',
    'Taguig',
    'Antipolo',
    'Pasig',
    'Cagayan de Oro',
    'Parañaque',
    'Valenzuela',
    'Bacoor',
    'General Santos',
    'Las Piñas',
    'Makati',
    'Bacolod',
    'Dasmariñas',
    'Iloilo City',
    'Calamba',
    'Marikina',
    'Muntinlupa',
    'Baguio',
    'Iligan',
    'Mandaue',
    'Butuan',
    'Cotabato City',
    'Lapu-Lapu City',
    'Legazpi',
    'Malolos',
    'San Jose del Monte',
    'Tarlac City',
    'Batangas City',
    'Cabanatuan',
    'Lucena',
    'Olongapo',
    'Puerto Princesa',
    'San Fernando (Pampanga)',
    'San Fernando (La Union)',
    'Tagaytay',
  ];
}

